### ISSUE TITLE
[BUG] `go-hass-agent --terminal register` does not create `preferences.toml`

### ISSUE THREAD

**Issue by Scandiravian** [joshuar/go-hass-agent#223] opened 2024-07-29 15:06 UTC
**Go Hass Agent Version**
v9.6.0

**Describe the bug**
When running `go-hass-agent register --terminal`  no `preferences.toml` is created. No logs are generated and the command exits with code 0

**To Reproduce**
Steps to reproduce the behaviour:
1. Get a token from Home Assistant
2. run `go-hass-agent register --terminal --token <token> --server <server_url>`
3. check whether the preferences file has been created with `test -f "$XDG_CONFIG_HOME/com.github.joshuar.go-hass-agent/preferences.toml`

**Expected behaviour**
- `go-hass-agent register --terminal` should create the `preferences.toml` file if successful registration or exit with a non-zero exit code if it fails.
- the command should output logs when running

**Logs**
No logs are created

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution: NixOS
 - Version: 24.05

**Additional context**
This could potentially be caused by running the agent under NixOS, since I've build and packaged `go-hass-agent` using `nix`.

I've also noticed that when running without the `--terminal` flag, the UI does not use the url set with the `--server` flag, only the token is set. Not sure if this is intended behaviour or is also a bug

**Comment by Gunni** [comment] 2024-07-31 10:18
Application tries to open `.config/com.github.joshuar.go-hass-agent/preferences.toml` with flags `O_RDONLY|O_CLOEXEC` and, if I make it, it reads it, then exits...

```strace
openat(AT_FDCWD, "/home/gunnar/.config/com.github.joshuar.go-hass-agent/preferences.toml", O_RDONLY|O_CLOEXEC) = 7
fcntl(7, F_GETFL)                       = 0x20000 (flags O_RDONLY|O_LARGEFILE)
fcntl(7, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 7, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=958398468, u64=9223049090632253444}}) = -1 EPERM (Operation not permitted)
fcntl(7, F_GETFL)                       = 0x20800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
fcntl(7, F_SETFL, O_RDONLY|O_LARGEFILE) = 0
fstat(7, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
read(7, "", 512)                        = 0
close(7)                                = 0
futex(0x4000069148, FUTEX_WAKE_PRIVATE, 1) = 1
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by joshuar** [comment] 2024-08-01 04:10
Thanks for trying out Go Hass Agent and oh dear, that's not a great first experience. Clearly some regression has crept in to the latest release. Does it also fail if you try the previous version?

In the latest code, I now have some more tests in place for the registration flow and in my manual testing, headless registration works. 

If the previous version works, that's awesome, stick with that until I get a new release out. Otherwise, if you are game, you can download one of the build artefacts from the latest commit [here](https://github.com/joshuar/go-hass-agent/actions/runs/10180225848) (scroll to the bottom of the page). Download the `build-linux-ARCH-*` archive for the `ARCH` you need. That'll contain all the packages and you can install with the one that you need.

**Comment by Erreur32** [comment] 2024-08-01 14:09
Same problem here with [v9.6.0](https://github.com/joshuar/go-hass-agent/releases/tag/v9.6.0) and  [v9.5.2](https://github.com/joshuar/go-hass-agent/releases/tag/v9.5.2)


i'm on  Linux Debian GNU/Linux 12 (bookworm).


With use of  `go-hass-agent_9.5.2_amd64.deb` and  `go-hass-agent_9.5.2_amd64.deb` , No input after register command
```
erreur32@Bma:~$ /usr/bin/go-hass-agent --terminal register --token n...o --server https://home.lan

erreur32@Bma:~$ /usr/bin/go-hass-agent --terminal version
4:01PM INF Go Hass Agent: v9.5.2
```

It create  only one empty log file is present in .config  `.config/go-hass-agent.log`

**Comment by joshuar** [comment] 2024-08-04 07:28
Thanks for testing the older version! I've done some testing as well. I can register with the `--terminal` option with v9.5.1, so I'm guessing that the preferences rewrite in v9.5.2 introduced this regression. 

For those affected, I would suggest going back to v9.5.1 for now, unless you can manually register with a UI first, as I don't believe UI registration is affected. You can then run headless after registering. Alternatively, using the pre-release build in my previous comment can be used, if you absolutely want the latest features.

**Comment by joshuar** [comment] 2024-08-26 04:24
Hey there, these issues should be fixed since [v10](https://github.com/joshuar/go-hass-agent/releases/tag/v10.0.0). I'll close this issue off, but please re-open if it is still a problem. Cheers!

**Closed by joshuar** 2024-08-26 04:24 UTC
Labels: bug
