### ISSUE TITLE
[BUG] Wrong config path for mqtt

### ISSUE THREAD

**Issue by dflvunoooooo** [joshuar/go-hass-agent#123] opened 2024-04-10 08:06 UTC
**Go Hass Agent Version**
v7.3.0

**Describe the bug**
If mqtt is enabled, I get an error message with a wrong path to the config file. It says `ERR Failed to register with MQTT. error="open /home/USER/.config/go-hass-anything/mqtt-config.toml: no such file or directory"`. But the config is in `/home/USER/com.github.joshuar.go-hass-agent/`. I don't know if my not working mqtt commands is related to that. 

**To Reproduce**
Steps to reproduce the behaviour:
1. run go-hass in terminal
2. set up mqtt connection
2. restart
3. watch output

**Expected behaviour**
I would expect to point to the correct config folder.

**Logs**
The log does not seem to include anything useful.
[go-hass-app.log](https://github.com/joshuar/go-hass-agent/files/14929479/go-hass-app.log)

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution Arch Linux
 - Version 6.8.4-arch1-1

**Additional context**
Fresh setup, nothing else configured.

**Comment by joshuar** [comment] 2024-04-11 00:13
Hey @dflvunoooooo that's super odd. It sounds like you might have some legacy configuration from an old version still lying around? I also wonder if that is an older log file and warning? Is the log file modified time old? Note that the log file location moved to `~/.local/state/go-hass-agent.log`, so any logs in the same directory as the config are older.  Did you set up MQTT with a previous version? 

7.3.0 should not be using `/home/USER/.config/go-hass-anything/mqtt-config.toml` at all and all MQTT settings should be in `/home/USER/.config/com.github.joshuar.go-hass-agent/preferences.toml`. From a fresh install on my own machine, I can verify that only  `/home/USER/.config/com.github.joshuar.go-hass-agent/preferences.toml` should exist after following the steps for both registering the agent and then subsequently setting up MQTT. 

Can you check the latter file and ensure, at the very least, the following settings are present:

```toml
'mqtt.server' = 'tcp://someserver:someport'
'mqtt.enabled' = true
```

That would at least indicate that 7.3.0 is set up with MQTT correctly.

**Comment by dflvunoooooo** [comment] 2024-04-11 08:27
Thank you for your answer. That seems impossible, since this is a fresh install. I haven't used go-hass-agent bevore. Ah, I was looking in a wrong directory for the log file, sorry! Here is the correct one.
[go-hass-agent.log](https://github.com/joshuar/go-hass-agent/files/14943388/go-hass-agent.log)
There are several mentions of 
```
{"level":"info","time":"2024-04-10T09:53:04+02:00","message":"Saved MQTT preferences."}
{"level":"error","error":"context canceled","time":"2024-04-10T09:53:14+02:00","message":"Could not start MQTT client."}
```
and then aga()
```
{"level":"error","error":"open /home/peter/.config/go-hass-anything/mqtt-config.toml: no such file or directory","time":"2024-04-10T09:53:17+02:00","message":"Failed to register with MQTT."}
```
with the strange `go-hass-anything` directory. I wonder where anything comes from. 

In the `preferences.toml` file I have the mqtt user and password and the following
```
'mqtt.server' = 'tcp://123.456.789.123:4567'
'mqtt.enabled' = true
'mqtt.registered' = false
```

Maybe deleting all folders and reinstalling will help.

**Comment by dflvunoooooo** [comment] 2024-04-11 08:45
Deleting the config folder, uninstalling, downloading and reinstalling the app did solve the problem with the wrong config path. Thank you for your help!

**Comment by dflvunoooooo** [comment] 2024-04-11 08:56
I am sorry, this was due to a config error on my side. Reinstall, and deletion didn't change the wrong config path for mqtt. Here is the log
[go-hass-agent.log](https://github.com/joshuar/go-hass-agent/files/14943846/go-hass-agent.log)

**Comment by joshuar** [comment] 2024-04-12 01:08
Okay, I have to say thank you, because you have uncovered a few bugs I didn't catch! I can now reproduce some of the issues you are having on my system. 

So it looks like you can register and connect to MQTT the first time and the controls will work. But then on a subsequent restart of the agent, they stop working 🙁 I get this behaviour on my machine and from your log file, it looks like this is what is happening for you. 

I'm working on a fix for this, so keep an eye out for the next release, hopefully very soon 🤞

As an aside, for some extra details, the "go-hass-anything" mentioned in the logs is [one of my other projects](https://github.com/joshuar/go-hass-anything). I re-use some Go packages from that project in the agent to avoid duplicate code. What you've also uncovered here is I need to improve the logging in these projects 😝

**Comment by joshuar** [comment] 2024-04-12 03:48
I believe this should be fixed now. At least for me, the MQTT functionality now works after restarting the agent. Can you try out the following snapshot and see if it also works for you?

[go-hass-agent-7.3.0SNAPSHOT_ea1500e-1-x86_64.zst.zip](https://github.com/joshuar/go-hass-agent/files/14953677/go-hass-agent-7.3.0SNAPSHOT_ea1500e-1-x86_64.zst.zip)

**Comment by dflvunoooooo** [comment] 2024-04-12 06:03
> Okay, I have to say thank you, because you have uncovered a few bugs I didn't catch! I can now reproduce some of the issues you are having on my system.
> …

You are welcome 😄 Sorry the result is so much work for you. 

I see, that explains, why there was no error after I connected. But it says I have to restart in the docs, is that still relevant?

Ah, that is where it is coming from! I was bamboozled from the anything part. 

> I believe this should be fixed now. At least for me, the MQTT functionality now works after restarting the agent. Can you try out the following snapshot and see if it also works for you?
> …

Yes, it is working 🎉 Great work, thank you! No errors about mqtt in the logs. Connection works after restart of go-hass-agent. And the buttons work and control my pc.

**Comment by joshuar** [comment] 2024-04-15 00:48
Great to hear this is now working. I'll close this issue off. You can continue using that snapshot build until the next release, that will also contain the fix.

Cheers!

**Closed by joshuar** 2024-04-15 00:48 UTC
Labels: bug
