### ISSUE TITLE
[BUG] Preferences area is empty

### ISSUE THREAD

**Issue by LeonardoCT** [joshuar/go-hass-agent#163] opened 2024-05-15 10:19 UTC
**Go Hass Agent Version**
(go-hass-agent: v9.0.0)

**Describe the bug**
Preference area is empty

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the program
2. Try to access settings

**Expected behaviour**
Accessing settings

**Screenshots**
![Istantanea_2024-05-15_12-10-14](https://github.com/joshuar/go-hass-agent/assets/20495117/49db7b6b-9982-4f90-bf53-4238a4133db3)

**Logs**
12:15PM DBG Debug logging enabled.
12:15PM DBG Setting language to [it].
12:15PM DBG Read sensor registry from disk.
12:15PM DBG Agent already registered.
12:15PM DBG Listening for notifications.
12:15PM DBG Starting worker funcs.
12:15PM DBG Could not find any script files.
12:15PM WRN Unable to monitor for active applications. No app tracking available.
12:15PM DBG Retrieved address. address=172.17.0.1 path=/org/freedesktop/NetworkManager/IP4Config/4 prefix=16
12:15PM DBG Monitoring connection state. connection="docker0 Connection State" path=/org/freedesktop/NetworkManager/ActiveConnection/2
12:15PM DBG Monitoring address changes. connection="docker0 Connection State" path=/org/freedesktop/NetworkManager/ActiveConnection/2
12:15PM DBG Retrieved address. address=192.168.1.54 path=/org/freedesktop/NetworkManager/IP4Config/2 prefix=24
12:15PM DBG Retrieved address. address=fd00::24c3:7fb3:f282:b7a6 path=/org/freedesktop/NetworkManager/IP6Config/2 prefix=64
12:15PM DBG Monitoring connection state. connection="Connessione via cavo 1 Connection State" path=/org/freedesktop/NetworkManager/ActiveConnection/1
12:15PM DBG Monitoring address changes. connection="Connessione via cavo 1 Connection State" path=/org/freedesktop/NetworkManager/ActiveConnection/1
12:15PM WRN Could not retrieve problem list. error="The name org.freedesktop.problems was not provided by any .service files"
12:15PM DBG Unable to retrieve property LidClosed (org.freedesktop.login1.Manager) error="dbus: invalid property LidClosed"
12:15PM WRN Could not retrieve lid status from D-Bus. Not tracking status. error="dbus: invalid property LidClosed"
12:15PM DBG Unable to retrieve property net.hadess.PowerProfiles.ActiveProfile (net.hadess.PowerProfiles) error="The name net.hadess.PowerProfiles was not provided by any .service files"
12:15PM DBG Cannot retrieve a power profile from D-Bus. Will not run power sensor. error="The name net.hadess.PowerProfiles was not provided by any .service files"
12:15PM WRN Unable to monitor for desktop settings. No accent color/theme tracking available.
12:15PM DBG Listening for location updates.
12:15PM DBG Listening for sensor updates.
12:15PM ERR Could not connect to websocket. error="dial tcp [REDACTED]: i/o timeout"

**Desktop**
 - OS: Linux
 - Distribution Linux Mint
 - Version 21.3

**Comment by joshuar** [comment] 2024-05-16 03:07
Hey this is super weird. I can reproduce this problem on a Linux Mint VM. I cannot reproduce on my Fedora desktop.  This might be a bug in the underlying GUI library (Fyne). I've opened an issue here:

https://github.com/fyne-io/fyne/issues/4843

Let's wait for some comments on that issue. I'm really unsure how the agent code could perform differently on different distributions in this way. Depending on the outcome of the above issue, I could workaround this by collapsing the Preferences menu into the main menu.

**Comment by joshuar** [comment] 2024-05-18 03:54
Hey there, I've merged the preferences menu items back into the main menu in [v9.1.1](https://github.com/joshuar/go-hass-agent/releases/tag/v9.1.1). Can you try it out and see if the options are now available for you?

**Comment by joshuar** [comment] 2024-06-17 22:51
Hey there, I'm going to close this off as the issue should have a workaround since v9.1.1. Do reply back if this is still an issue though and we can look into it further.

**Closed by joshuar** 2024-06-17 22:51 UTC
Labels: bug
