### ISSUE TITLE
MQTT auto-reconnect

### ISSUE THREAD

**Issue by jaynis** [joshuar/go-hass-agent#125] opened 2024-04-10 20:52 UTC
Hi. I sometimes experience that MQTT stops working. Unfortunately I do not have much more information apart from that messages sent to the `go-hass-agent` are not received anymore. In my case this sometimes happens after I wake up my computer from hibernation or after it was idling for a long period of time (some hours). When I restart the agent in such situation it immediately works again afterwards. Therefore I was wondering whether it would be possible to introduce some kind of auto-reconnect mechanism within the agent. The [eclipse/paho.mqtt.golang](https://github.com/eclipse/paho.mqtt.golang) lib which is used for the MQTT functionality offers a `SetAutoReconnect()` option. Do you think it would be beneficial to enabled that?

**Comment by joshuar** [comment] 2024-04-11 00:32
Yes definitely! I thought the connection **did already** have some kind of autoconnect, or at least, keep-alive method, but now I am not sure. I will look into this.

**Comment by joshuar** [comment] 2024-04-12 03:46
So it turns out that no, autoconnect wasn't implemented 🙁 I've implemented it now and seems to work for me when I suspend/resume.  Would you be able to test the following snapshot build to see if it works for you? 

[go-hass-agent-7.3.0~SNAPSHOT-ea1500e-1.x86_64.rpm.zip](https://github.com/joshuar/go-hass-agent/files/14953665/go-hass-agent-7.3.0.SNAPSHOT-ea1500e-1.x86_64.rpm.zip)
[go-hass-agent_7.3.0~SNAPSHOT-ea1500e-1_amd64.deb.zip](https://github.com/joshuar/go-hass-agent/files/14953667/go-hass-agent_7.3.0.SNAPSHOT-ea1500e-1_amd64.deb.zip)
[go-hass-agent-7.3.0SNAPSHOT_ea1500e-1-x86_64.zst.zip](https://github.com/joshuar/go-hass-agent/files/14953669/go-hass-agent-7.3.0SNAPSHOT_ea1500e-1-x86_64.zst.zip)

**Comment by jaynis** [comment] 2024-04-12 20:02
Thank you for looking into this! Unfortunately I am already on a custom build right now which I have created myself :smile: (not related to this issue). So I have to merge my changes with your changes first to build a combined version. I will let you know the outcome.

**Comment by dflvunoooooo** [comment] 2024-04-15 10:00
I have the same problem. But I can not test this, due to #123. Is it possible to combine both solution?

**Comment by joshuar** [comment] 2024-04-16 00:01
Hey @dflvunoooooo, the snapshot in #123 and above (they are the same) should fix these issues. Are you still seeing a case of the actions not working after a restart of either Home Assistant or MQTT?

**Comment by dflvunoooooo** [comment] 2024-04-17 07:11
No, your fix seems to solve the problem, for me at least.

**Comment by joshuar** [comment] 2024-04-17 22:21
Excellent! Thank you for circling back!

**Comment by joshuar** [comment] 2024-04-27 06:19
I'm going to close this issue off on the assumption that the problem is fixed. In my manual usage/testing, the new code is ensuring the agent reconnects as necessary, when it either loses a connection to MQTT or Home Assistant is restarted.

If this is still an issue, please re-open and we can investigate further.

**Closed by joshuar** 2024-04-27 06:19 UTC
Labels: enhancement
