### ISSUE TITLE
[BUG] go-hass-agent_10.2.0_amd64.deb  Required Xorg dependancy 

### ISSUE THREAD

**Issue by Erreur32** [joshuar/go-hass-agent#276] opened 2024-09-13 08:06 UTC
**Go Hass Agent Version**
go-hass-agent_10.2.0_amd64.deb 

**Describe the bug**
When we install with : dpkg -i go-hass-agent_10.2.0_amd64.deb  , go-hass-agent depends on xorg , and i don't want Xorg on my server.

 **Logs**
```bash
dpkg -i  go-hass-agent_10.2.0_amd64.deb

(Lecture of the database... 113268 files and directories already installed.)
Preparing to unpack go-hass-agent_10.2.0_amd64.deb ...
Unpacking go-hass-agent (10.2.0) over (10.0.1) ...
dpkg: dependency problems prevent configuration of go-hass-agent:
 go-hass-agent depends on xorg; however:
  Package xorg is not installed.

dpkg: error processing package go-hass-agent (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1) ...
Errors were encountered while processing:
 go-hass-agent
```

With the old one ( in french ) the installation was successfully : 
```bash
dpkg -i go-hass-agent_10.0.1_amd64.deb

dpkg: avertissement: dégradation (« downgrade ») de go-hass-agent depuis 10.1.1 vers 10.0.1
(Lecture de la base de données... 113738 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de go-hass-agent_10.0.1_amd64.deb ...
Dépaquetage de go-hass-agent (10.0.1) sur (10.1.1) ...
Paramétrage de go-hass-agent (10.0.1) ...
Traitement des actions différées (« triggers ») pour mailcap (3.70+nmu1) ...
```

Information:  I don't have any graphical interface on my servers. Possible to bypass this ? 
With old version no need Xorg to install Go-Hass-Agent. It is required now ?
Possible to remove any relation with Xorg ?

Thanks you for your hard work.

**Comment by joshuar** [comment] 2024-09-16 05:01
Hey @Erreur32 thanks for reporting this. I had adjusted the dependencies based off the list the Fyne library (which powers the UI) has listed, but the dependencies for Debian/Ubuntu specify the `xorg` package, which probably pulls in too much. I've re-adjusted the dependencies to be explicit to which libraries are actually compiled in to the binary, so it should be back to the previous functionality. This is in [v10.2.1](https://github.com/joshuar/go-hass-agent/releases/tag/v10.2.1). Can you try that version out and let me know if it results in less other dependencies being pulled in?

**Comment by joshuar** [comment] 2024-09-30 04:42
Hey @Erreur32 just following up. Those panics are gross but harmless 😜 I have reworked the disk usage sensors to filter out more mount points which are the cause of them. So hopefully in the next release, you should see none or far less of the panics 🎉

**Comment by joshuar** [comment] 2024-10-12 00:57
Hey there, I believe the latest version has sorted out the dependency issue. I'll close this issue off but please re-open if there is still a dependency problem with the package!

**Closed by joshuar** 2024-10-12 00:57 UTC
Labels: bug
