### ISSUE TITLE
[BUG] go-hass-agent version not working 

### ISSUE THREAD

**Issue by Erreur32** [joshuar/go-hass-agent#202] opened 2024-07-04 09:24 UTC
**Go Hass Agent Version**
Retrieve with `go-hass-agent version`.   i can't ...
but i tried with the latest : V9.5.1 yesterday

**Describe the bug**
this is the bug , no version appear when i do go-hass-agent version

I'm on Debian 12 and used  the .tar.xz.

**To Reproduce**
Steps to reproduce the behaviour:
```
 su user -c "/home/duser/.local/bin/go-hass-agent  --terminal  version"
 INF Go Hass Agent:
```
 
it was working well with v9.2.0 ;) , other version after i don't know.

Thanks

**Comment by joshuar** [comment] 2024-07-07 00:38
Hey thanks for trying out Go Hass Agent. I can confirm the tar.xz packages have this bug. It might be a little tricky to fix. The good news though is the deb package is built on Ubuntu 22.04, which is compatible with Debian 12. I can confirm that on a Debian 12 VM, installing the deb package works (including the version command).

Can you try the deb package and let me know if that works for you?

**Comment by Erreur32** [comment] 2024-07-07 08:47
Thanks for your reply !
 
 Yes with **.deb** it working :)
   -->  i needed to install also **dbus-x11** , which i don't have it before. 

su debian32 -c  "/usr/bin/go-hass-agent version --terminal"
10:35AM INF Go Hass Agent: v9.5.1

i have also registered again cause path was change . 

Can we keep .deb for Debian 12 in next release ?  fine for me ;)

Thanks

**Comment by Erreur32** [comment] 2024-07-07 10:09
Sorry bad new after some time have this error:

2024-07-07 11:52:12.013 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: not a valid value for dictionary value @ data['device_class']. Got 'DeviceClass(0)'
2024-07-07 11:52:12.014 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: not a valid value for dictionary value @ data['device_class']. Got 'DeviceClass(0)'

I have also not all sensors detected 30 instedd of 90

i have revert back to 9.2.0 , and error gone and all sensors are back.

**Comment by joshuar** [comment] 2024-07-07 11:38
Ah! I also noticed this problem with the sensors, a regression has stuck in that should be fixed by https://github.com/joshuar/go-hass-agent/commit/022c80f239154d293cf8631fc2ecdd9e3d58bd63 in the next release. Glad to hear that switching back to an older release is a workaround. Look out for the next release in the next few days!

Yep on using the deb for Debian! I'll update the README as well. 

Side note: I believe I originally had to start publishing the tar.xz packages as my build system resulted in deb packages that couldn't run on Debian, only Ubuntu. A lot has changed since then and the current build process has better compatibility it seems!

**Comment by joshuar** [comment] 2024-08-01 04:13
I'm going to close this issue off as I believe the issue is now resolved. If that is not the case please reply back to re-open with any further details!

**Closed by joshuar** 2024-08-01 04:13 UTC
Labels: bug
