### ISSUE TITLE
[BUG] Crash after standby

### ISSUE THREAD

**Issue by akentner** [joshuar/go-hass-agent#61] opened 2023-12-09 15:09 UTC
**Describe the bug**
After resume of standby, the program crashes with error:

```
...
3:59PM DBG Sensor updated. id=bytes_sent_throughput name="Bytes Sent Throughput" state="1786 B/s"
panic: runtime error: index out of range [1] with length 1

goroutine 242 [running]:
github.com/joshuar/go-hass-agent/internal/linux.BatteryUpdater.func1(0xc00031bfa8?)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/batterySensor.go:365 +0x50f
github.com/joshuar/go-hass-agent/pkg/dbushelpers.(*busRequest).AddWatch.func1()
	/home/runner/work/go-hass-agent/go-hass-agent/pkg/dbushelpers/dbus.go:207 +0xa2
created by github.com/joshuar/go-hass-agent/pkg/dbushelpers.(*busRequest).AddWatch
	/home/runner/work/go-hass-agent/go-hass-agent/pkg/dbushelpers/dbus.go:198 +0x151

```

**To Reproduce**
1. start `go-hass-agent --debug`
2. standby the computer
3. resume the computer
4. program crashes

**Expected behavior**
Program also resumes after standby

**Logs**

```
...
3:59PM DBG Sensor updated. id=bytes_sent_throughput name="Bytes Sent Throughput" state="1786 B/s"
panic: runtime error: index out of range [1] with length 1

goroutine 242 [running]:
github.com/joshuar/go-hass-agent/internal/linux.BatteryUpdater.func1(0xc00031bfa8?)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/batterySensor.go:365 +0x50f
github.com/joshuar/go-hass-agent/pkg/dbushelpers.(*busRequest).AddWatch.func1()
	/home/runner/work/go-hass-agent/go-hass-agent/pkg/dbushelpers/dbus.go:207 +0xa2
created by github.com/joshuar/go-hass-agent/pkg/dbushelpers.(*busRequest).AddWatch
	/home/runner/work/go-hass-agent/go-hass-agent/pkg/dbushelpers/dbus.go:198 +0x151

```

**Desktop:**
 - Ubuntu 23.10.1 
 - Dell Latitude 5511
 - `go-hass-agent` v5.3.1

**Comment by joshuar** [comment] 2023-12-11 01:33
Thank you for trying out go-hass-agent and the debug logs. I can see what the problem is here, another unprotected type assertion. I've fixed this (https://github.com/joshuar/go-hass-agent/commit/8eff8830ef4ce8e2c53145087c19821f63a96d6d) and it'll go into the next version. Thank you for reporting!

**Comment by akentner** [comment] 2023-12-11 21:29
For sure, I'll keep on testing ;-)

**Comment by joshuar** [comment] 2023-12-14 12:10
Hey @akentner, [v6.0.1](https://github.com/joshuar/go-hass-agent/compare/v6.0.0...v6.0.1) has been released which should also fix this issue. Can you give it a try when you get a chance and report back?

**Comment by akentner** [comment] 2023-12-14 13:47
Hey, 

I just installed 6.0.1 and reproduced my steps above. I got a slightly other error:

```
...
2:41PM DBG Sensor updated. id=wi_fi_signal_strength name="Wi-Fi Signal Strength" state="71 %"
panic: runtime error: index out of range [1] with length 1

goroutine 80 [running]:
github.com/joshuar/go-hass-agent/internal/linux.BatteryUpdater.func1(0xc0008cffa8?)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/batterySensor.go:322 +0x334
github.com/joshuar/go-hass-agent/pkg/dbushelpers.(*busRequest).AddWatch.func1()
	/home/runner/work/go-hass-agent/go-hass-agent/pkg/dbushelpers/dbus.go:203 +0x8f
created by github.com/joshuar/go-hass-agent/pkg/dbushelpers.(*busRequest).AddWatch in goroutine 15
	/home/runner/work/go-hass-agent/go-hass-agent/pkg/dbushelpers/dbus.go:194 +0x145
```

`2:41PM DBG Sensor updated. id=wi_fi_signal_strength` was the last event befor standby.

**Comment by clarjon1** [comment] 2023-12-15 16:26
I can also replicate the crash upon resume with the latest release:

```
11:25AM DBG Sensor updated. id=wi_fi_signal_strength name="Wi-Fi Signal Strength" state="68 %"
panic: runtime error: index out of range [1] with length 1

goroutine 65 [running]:
github.com/joshuar/go-hass-agent/internal/linux.BatteryUpdater.func1(0xc000627fa8?)
        /home/runner/work/go-hass-agent/go-hass-agent/internal/linux/batterySensor.go:322 +0x334
github.com/joshuar/go-hass-agent/pkg/dbushelpers.(*busRequest).AddWatch.func1()
        /home/runner/work/go-hass-agent/go-hass-agent/pkg/dbushelpers/dbus.go:203 +0x8f
created by github.com/joshuar/go-hass-agent/pkg/dbushelpers.(*busRequest).AddWatch in goroutine 14
        /home/runner/work/go-hass-agent/go-hass-agent/pkg/dbushelpers/dbus.go:194 +0x145
```

**Comment by joshuar** [comment] 2023-12-16 01:43
I can see what the problem is here. I recently discovered that when you add D-Bus watches, all watches get all data from every other watch. I was expecting a particular watch to only receive the data it was watching for. The battery sensor code was written this way. I've fixed it up and [v6.0.2](https://github.com/joshuar/go-hass-agent/releases/tag/v6.0.2) should resolve this problem. 

Can you try it out?

**Comment by clarjon1** [comment] 2023-12-16 06:18
v6.0.2 does prevent the crash for me on my end!

**Comment by joshuar** [comment] 2024-01-30 08:24
Hey this issue is fairly old and it looks like at least one other user has reported the crash as fixed. I'm going to close this issue off, but please do try with the latest version of the agent, which should have the required fix. If it is still an issue with the latest version, please feel free to re-open this issue.

**Closed by joshuar** 2024-01-30 08:24 UTC
