### ISSUE TITLE
go-hass-agent errors out on first run

### ISSUE THREAD

**Issue by mwright-git** [joshuar/go-hass-agent#108] opened 2024-02-28 01:22 UTC
**Go Hass Agent Version**
7.1.0

**Describe the bug**
go-hass-agent errors out after entering required info

**To Reproduce**
Steps to reproduce the behaviour:
1. Execute go-hass-agent
2. Enter details
3. Hit continue
4. See error.

**Expected behaviour**
Not exactly sure - but not the error.

**Screenshots**

**Logs**
[mwright yoda go hass agent.txt.gz](https://github.com/joshuar/go-hass-agent/files/14427396/mwright.yoda.go.hass.agent.txt.gz)

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution Ubuntu
 - Version 24.1

**Additional context**

**Comment by joshuar** [comment] 2024-02-28 05:19
Hey @mwright-git, thanks for trying out go-hass-agent. That's not a great first experience and definitely not expected behaviour!  I've taken a look at the logs but there isn't any good leads there, but we can increase the logging level which might reveal some more details.

Could you try the following:

- run `go-hass-agent reset` to remove the configuration and log files.
- run go-hass-agent --trace` to run the agent with trace logging enabled (see below for additional caveat). This will go through a new registration process as you will have wiped the existing one with the previous command.

Once it (presumably) crashes again, can you attach the agent log file? Can you also check and extract any relevant error messages from the Home Assistant log (see Settings -> System -> Logs in Home Assistant).

**Caveat on trace logging:**
Note that the trace log will contain some private details, like the Home Assistant URL and potentially an ID used to send requests to Home Assistant; you may wish to remove those details before uploading (I don't need the URL or the ID). An example log line with the private information will look like:

```
3:17PM TRC Sending request. body={"data":[{"attributes":{"Data Source":"SysFS","Sensor Type":"Alarm"},"icon":"mdi:alarm-light-off","state":false,"type":"binary_sensor","unique_id":"alarm_coretemp_temp_26_crit_alarm"}],"type":"update_sensor_states"} method=POST sent_at=2024-02-28T15:17:07+10:00 url=http://YOUR_HA_URL/api/webhook/A_SECRET_WEBHOOKID
```

You can remove `YOUR_HA_URL` and `A SECRET_WEBHOOKID` in those lines and similar ones

**Comment by TobiasBitter** [comment] 2024-02-28 06:34
Also not running on my machine. May be related.
Linux Mint 21.3 Cinnamon
6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC
[go-hass-agent-error-log.txt](https://github.com/joshuar/go-hass-agent/files/14429809/go-hass-agent-error-log.txt)

**Comment by joshuar** [comment] 2024-02-28 23:04
Oh dear! Thank you @TobiasBitter for your trace log, that is very helpful and I believe I can see the flow that is causing this. I was able to recreate a related (potentially the same) problem on my machine as well. I've implemented a fix (https://github.com/joshuar/go-hass-agent/commit/68b18dc016cf4335a8b50751c757096b1cf0cd11) that should solve this.

The following zip contains a snapshot build (and signature for verification with cosign if desired) I created with the fix included. 

[go-hass-agent_7.1.0~SNAPSHOT-68b18dc-1_amd64.zip](https://github.com/joshuar/go-hass-agent/files/14440709/go-hass-agent_7.1.0.SNAPSHOT-68b18dc-1_amd64.zip)

Would you both be able to try out this snapshot build? It might be worth trying to run it first with trace logging enabled again. If you are seeing lots of errors and no updates in Home Assistant, try the reset command then have the agent re-register. I'm betting it either works first without a reset or after in any case :crossed_fingers:

**Comment by mwright-git** [comment] 2024-02-28 23:55
Hmmm - I have tried your snapshot build and whilst it now seems to
complete the registration and remain running, I can't see any data in
Home Assistant.

I tried it first with the default connection (log1) and then I tried
mqtt connection (log2) With the mqtt I can see a couple of entries
(buttons) but that it all.

Mike

**Comment by joshuar** [comment] 2024-02-29 03:13
Hey @mwright-git it doesn't look like the logs you mentioned are attached? A few things to try:

- Stop the agent, and run `go-hass-agent reset`. Then start the agent again, allowing it to re-register.
- If that still fails. Stop the agent, and remove the agent device entry in the Home Assistant mobile integration settings. Then run `for-hass-agent reset`. Then start the agent and re-register.

I was able to bring up an Ubuntu 22.04 desktop in a VM, install the snapshot and register so I'm hoping either of the above will help for you by ensuring everything is in a clean slate.

**Comment by mwright-git** [comment] 2024-02-29 14:28
[log1.txt](https://github.com/joshuar/go-hass-agent/files/14449278/log1.txt)
[log2.txt](https://github.com/joshuar/go-hass-agent/files/14449281/log2.txt)

**Comment by joshuar** [comment] 2024-03-01 00:18
Thanks @mwright-git for those logs. 

Aha! I think I see the issue. I've set a rather aggressive timeout for sending requests to Home Assistant. I will increase this to something more generous. 

Just out of curiosity, can you run the following curl command to check a rough time to connect to your Home Assistant:

```shell
curl -so /dev/null -w "total:  %{time_total}s\n" "http://localhost:8123"
```

The output might show a time that is close to or greater than 1 second?

**Comment by mwright-git** [comment] 2024-03-01 00:25
I ran it a few times and got consistently less than 0.2 secs

**Comment by joshuar** [comment] 2024-03-01 05:00
Interesting! 

Actually I misread the log file, when using Home Assistant Cloud, requests are posted to https://hooks.nabu.casa by the looks of it, which I assume is the same for all users (with some unique path appended and user authentication).  For me, the connection time to that URL is pretty consistently within 0.5s, but it likely varies widely per user, or might be rate-limited, round-robin, or some other routing that causes some big variation in timings for some reason.

Attached is a new snapshot with a much larger request timeout, that should hopefully cover any extreme variation in response time from https://hooks.nabu.casa. Can you try out this version and let me know if it allows updates from the agent to appear in Home Assistant?

[go-hass-agent_7.1.0~SNAPSHOT-319e220-1_amd64.zip](https://github.com/joshuar/go-hass-agent/files/14456529/go-hass-agent_7.1.0.SNAPSHOT-319e220-1_amd64.zip)

**Comment by TobiasBitter** [comment] 2024-03-01 08:53
I've tested the new build and it is working - more or less.
Preferences are not acceable via GUI. There are plenty of errors in the trace log.
And only a hand full of entities are shown in Home Assistant. Is it supposed to work that way?
![Bildschirmfoto vom 2024-03-01 09-50-06](https://github.com/joshuar/go-hass-agent/assets/36224803/3a24b8bb-ecaa-45cc-b3d9-7d9c35b5d205)

[go-hass-agent710-error-log.txt](https://github.com/joshuar/go-hass-agent/files/14458642/go-hass-agent710-error-log.txt)

**Comment by joshuar** [comment] 2024-03-02 00:04
Thanks for the log @TobiasBitter. It's definitely not meant to work that way :frowning_face:  In your case, I believe the agent thinks that sensors its reporting are registered, but Home Assistant is returning a response saying they are not. I reckon because of the timeout issues in the earlier snapshot/version, you've got a mismatch between the agent and Home Assistant sensor registration statuses. 

If you run `go-hass-agent reset` it will remove the database the agent stores for sensor registration status. You'll need to register the agent again, but it should work correctly after that. If you get any errors or warnings from the reset command, you can try manually deleting the `~/.config/go-hass-agent` directory and then allowing the agent to register again.  

As to the App Preferences menu not showing, thats new to me and very bizarre! I wonder if you watch your journal (journalctl -f) and then try to open the menu, do you see any related error or warning messages triggered as you are doing it? I'll have to see if I can reproduce that issue, but I'm also wondering if this is a symptom of the above weird state the agent is in...

**Comment by TobiasBitter** [comment] 2024-03-04 09:52
I performed go-hass-agent reset followed by manual deletion of the corrosponding device in HA.
After a re-registration everything works as expected. :-)
Tanks!

**Comment by joshuar** [comment] 2024-03-04 22:35
Brilliant! Thanks @TobiasBitter for the circle back, I'm so glad it is now working properly. And thanks again for the perseverance and details/logs you provided, those were crucial to helping me solve this issue. 

I'll leave this open for now in case @mwright-git is still having issues. Cheers!

**Comment by joshuar** [comment] 2024-04-10 00:18
I'm going to close this issue off on the assumption this is now fixed from the feedback here. If it is still an issue, please re-open and we can resume troubleshooting.

Thanks!

**Closed by joshuar** 2024-04-10 00:18 UTC
Labels: bug
