### ISSUE TITLE
[BUG] v10.1.1 crashes at startup

### ISSUE THREAD

**Issue by fdw** [joshuar/go-hass-agent#266] opened 2024-09-05 17:37 UTC
**Go Hass Agent Version**
`v10.1.1`

**Describe the bug**
After startup, it crashes:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd02e0c]
goroutine 77 [running]:
github.com/joshuar/go-hass-agent/internal/linux/mem.newMemSensor(0xe82100?, 0x0)
        /home/runner/work/go-hass-agent/go-hass-agent/internal/linux/mem/memUsage.go:66 +0x7c
github.com/joshuar/go-hass-agent/internal/linux/mem.(*usageWorker).Sensors(0x0?, {0x0?, 0x400044c5f8?}, 0x4665f0?)
        /home/runner/work/go-hass-agent/go-hass-agent/internal/linux/mem/memUsage.go:108 +0x11c
github.com/joshuar/go-hass-agent/internal/linux.(*SensorWorker).handlePolling.func1(0x0?)
        /home/runner/work/go-hass-agent/go-hass-agent/internal/linux/worker.go:135 +0x4c
github.com/joshuar/go-hass-agent/internal/device/helpers.PollSensors({0x1199f40, 0x40000a1090}, 0x400007e7c0, 0xdf8475800, 0x12a05f200)
        /home/runner/work/go-hass-agent/go-hass-agent/internal/device/helpers/polling.go:22 +0x50
github.com/joshuar/go-hass-agent/internal/linux.(*SensorWorker).handlePolling.func2()
        /home/runner/work/go-hass-agent/go-hass-agent/internal/linux/worker.go:148 +0xa8
created by github.com/joshuar/go-hass-agent/internal/linux.(*SensorWorker).handlePolling in goroutine 42
        /home/runner/work/go-hass-agent/go-hass-agent/internal/linux/worker.go:146 +0x140
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Install latest version from deb
2. Start `go-hass-agent`

**Expected behaviour**
It doesn't crash 😉

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution: Manjaro

**Comment by sugarfunk** [comment] 2024-09-06 03:38
I think I am having the same

```
Sep  5 23:01:14.948 DEBUG Setting language. lang=[en-US]
Sep  5 23:01:14.949 DEBUG Read sensor registry from disk. file=sensor.reg
Sep  5 23:01:14.953 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor for active applications: no portal present"
Sep  5 23:01:14.953 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor for desktop settings: no portal present"
Sep  5 23:01:14.953 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor location updates: unsupported hardware"
Sep  5 23:01:14.953 WARN Could not start a sensor worker. linux.controller=sensor error="unable to monitor laptop sensors: unsupported hardware"
Sep  5 23:01:14.953 DEBUG Processing sensor updates.
Sep  5 23:01:14.953 WARN Sensor not found in registry. sensor_id=agent_version
Sep  5 23:01:14.953 WARN Sensor not found in registry. sensor_id=agent_version
Sep  5 23:01:14.954 WARN Sensor not found in registry. sensor_id=memory_total
Sep  5 23:01:14.954 WARN Sensor not found in registry. sensor_id=memory_total
Sep  5 23:01:14.954 WARN Sensor not found in registry. sensor_id=cpu_load_average_(5_min)
Sep  5 23:01:14.954 WARN Sensor not found in registry. sensor_id=cpu_load_average_(5_min)
Sep  5 23:01:14.954 WARN Sensor not found in registry. sensor_id=memory_free
Sep  5 23:01:14.954 WARN Sensor not found in registry. sensor_id=memory_free
Sep  5 23:01:14.955 WARN Sensor not found in registry. sensor_id=bytes_received
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=bytes_received
Sep  5 23:01:14.956 WARN Unable to retrieve sensors. worker=abrt_problems_sensor worker_type=polling error="unable to retrieve the list of ABRT problems: SystemBus: unable to get data org.freedesktop.problems.GetProblems from org.freedesktop.problems: The name org.freedesktop.problems was not provided by any .service files"
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=sda_disk_writes
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=cpu_load_average_(1_min)
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=mountpoint_run
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=sda_disk_reads
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=bytes_sent
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=bytes_sent
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=sda_disk_reads
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=swap_free
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=swap_free
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=distribution_name
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=mountpoint_root
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=distribution_version
Sep  5 23:01:14.956 WARN Sensor not found in registry. sensor_id=total_disk_reads
Sep  5 23:01:14.957 WARN Sensor not found in registry. sensor_id=total_disk_reads
Sep  5 23:01:14.957 WARN Sensor not found in registry. sensor_id=core_1_cpu_usage
Sep  5 23:01:14.957 WARN Sensor not found in registry. sensor_id=core_1_cpu_usage
Sep  5 23:01:14.957 WARN Sensor not found in registry. sensor_id=cpufreq_core2_frequency
Sep  5 23:01:14.957 WARN Sensor not found in registry. sensor_id=core_3_cpu_usage
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xddfd6e]

goroutine 89 [running]:
github.com/joshuar/go-hass-agent/pkg/linux/hwmon.GetAllSensors()
	/home/runner/work/go-hass-agent/go-hass-agent/pkg/linux/hwmon/hwmon.go:459 +0xae
github.com/joshuar/go-hass-agent/internal/linux/system.(*hwMonWorker).Sensors(0xc00046a080, {0x0?, 0x0?}, 0x0?)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/system/hwmon.go:119 +0x27
github.com/joshuar/go-hass-agent/internal/linux.(*SensorWorker).handlePolling.func1(0x0?)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/worker.go:135 +0x4b
github.com/joshuar/go-hass-agent/internal/device/helpers.PollSensors({0x1285310, 0xc0004728c0}, 0xc0003a2a80, 0xdf8475800, 0x12a05f200)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/device/helpers/polling.go:22 +0x68
github.com/joshuar/go-hass-agent/internal/linux.(*SensorWorker).handlePolling.func2()
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/worker.go:148 +0xac
created by github.com/joshuar/go-hass-agent/internal/linux.(*SensorWorker).handlePolling in goroutine 29
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/worker.go:146 +0x14f
```

**Comment by joshuar** [comment] 2024-09-07 01:26
Hey @fdw, that'd be caused by me forgetting to be more diligent in checking for the different memory sensor availability 😓 Fixed with 295a893897005d4f359107fb0f8312d99e3e3dbb.

@sugarfunk, I think I have a fix for that with 1704d3303736330186e8b4b53c1ee99515fb83fe.

You can try out a pre-release with these fixes by downloading the archive for your architecture from [the last CI run](https://github.com/joshuar/go-hass-agent/actions/runs/10747412580). At the bottom of that page, in the **Artifacts** section, pick the ***build-linux-ARCH-HASH*** file for your ARCH (for normal desktops/laptops, that'll be ***amd64***). The download will be an zip archive containing all the packages for that architecture, please use the appropriate one for your distro.

If you do use the pre-release, please report back whether it fixes the issue or not!

**Comment by sugarfunk** [comment] 2024-09-07 05:16
@joshuar Mine seems to be working!

**Comment by fdw** [comment] 2024-09-07 07:46
Yep, it works now. Thank you!

**Comment by sugarfunk** [comment] 2024-09-07 18:47
@joshuar Spoke too soon. It just moved on to a new one.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xe1deee]

goroutine 127 [running]:
github.com/joshuar/go-hass-agent/pkg/linux/hwmon.GetAllSensors()
	/home/runner/work/go-hass-agent/go-hass-agent/pkg/linux/hwmon/hwmon.go:459 +0xae
github.com/joshuar/go-hass-agent/internal/linux/system.(*hwMonWorker).Sensors(0x0?, {0x1293650, 0xc00016b9a0}, 0x0?)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/system/hwmon.go:108 +0x32
github.com/joshuar/go-hass-agent/internal/linux.(*SensorWorker).handlePolling.func1(0x0?)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/worker.go:141 +0x4b
github.com/joshuar/go-hass-agent/internal/device/helpers.PollSensors({0x1293650, 0xc00016b9a0}, 0xc000056740, 0xdf8475800, 0x12a05f200)
	/home/runner/work/go-hass-agent/go-hass-agent/internal/device/helpers/polling.go:22 +0x68
github.com/joshuar/go-hass-agent/internal/linux.(*SensorWorker).handlePolling.func2()
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/worker.go:154 +0xa6
created by github.com/joshuar/go-hass-agent/internal/linux.(*SensorWorker).handlePolling in goroutine 107
	/home/runner/work/go-hass-agent/go-hass-agent/internal/linux/worker.go:152 +0x14f
```

**Comment by joshuar** [comment] 2024-09-10 04:08
Hey @sugarfunk. Hmm, I kinda have a feeling of what is wrong, but would you be able to do a check for me? 

Are you confident with Git and Go? If so, could you clone the Go Hass Agent repo, then run `go run pkg/linux/hwmon/examples/getAllSensors.go` from inside the repo? That will print all hardware sensors on your device and any errors encountered. Could you copy the output on this issue?

If not, I could provide an executable of this code for you to run.

**Comment by joshuar** [comment] 2024-09-13 04:05
Hey @sugarfunk, I've released [v10.2](https://github.com/joshuar/go-hass-agent/releases/tag/v10.2.0) which contains some refactored code for gathering the hardware sensors which seem to be crashing for you. I would be keen to see how that version fares for you. When you get the chance, please try it out and report back!

**Comment by sugarfunk** [comment] 2024-09-14 04:23
@joshuar I'll give 1.02 a shot in the AM and if no go, I'll run the get sensors code. I might be an edge case so don't down a wormhole for me. I'm running a 2019 iMac running debian bookworm. Apple does odd stuff.

**Comment by joshuar** [comment] 2024-09-30 04:45
Hey folks, I'm going to close this issue off for now. If we start to see more regular occurrences of race conditions that look to be related, we can re-open. For the meantime, I think we've solved the problems here and folks have functioning versions? Please re-open if that is not the case!

**Closed by joshuar** 2024-09-30 04:45 UTC
Labels: bug
